Progress Bar Added
avincodes/Web-dev-Snippets pull request #53
Opened 2022-10-15 13:34 UTC by arhab2001

I have added Progress bar

2022-10-15 14:12 UTC, avincodes requested changes
Please add a readme file with a screenshot of your snippet in action!

2022-10-16 07:33 UTC, avincodes requested changes

2022-10-16 07:33 UTC, avincodes commented on Readme.md
> +## Screenshot
- [ ] Make the title the name of your snippet.

2022-10-16 12:26 UTC, Safnaj commented
@avincodes better to add these as guidelines in the main readme file rather than forcing the contributors in the pull requests. It will make ur work easy though.

2022-10-16 14:22 UTC, avincodes commented
Yep! I have a contributors guidelines file to be created as an issue @Safnaj!

> @avincodes better to add these as guidelines in the main readme file rather than forcing the contributors in the pull requests. It will make ur work easy though.

2022-10-16 14:28 UTC, avincodes approved these changes
Good to go!

2022-10-16 14:29 UTC, avincodes commented
Thank you for your pull request @arhab2001!

2022-10-16 14:29 UTC, merged