added the text hover effect #54
avincodes/Web-dev-Snippets pull request #57
Opened 2022-10-15 14:58 UTC by prat1k-gupta

2022-10-15 15:13 UTC, avincodes requested changes
Please add a readme file containing a screenshot of the snippet in action! Thanks!

2022-10-15 17:51 UTC, prat1k-gupta commented
Added readme

2022-10-16 07:31 UTC, avincodes approved these changes
Good to go!

2022-10-16 07:31 UTC, avincodes commented
Thank you for your pull request @prat1k-gupta! Great work!

2022-10-16 07:32 UTC, merged